//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERVER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conversation
    {
        public Conversation()
        {
            this.ConversationUser = new HashSet<ConversationUser>();
            this.Conversation1 = new HashSet<Message>();
        }
    
        public int idConversation { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<ConversationUser> ConversationUser { get; set; }
        public virtual ICollection<Message> Conversation1 { get; set; }
    }
}
